### PR TITLE
Fix issue 251

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@bmwiedemann I think this resolves the issue, can you confirm?

**Comment by bmwiedemann** [comment]
I tried to test this patch, but it seems, our unchanged `libsemigroups` 1.3.3 package stopped building during the last weeks

2020-10-10 still had a successful build
2020-10-19 had the first failed build

log:
```
 libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./config -DNDEBUG -I/home/abuild/rpmbuild/BUILD/libsemigroups-1.3.3/include -I/home/abuild/rpmbuild/BUILD/libsemigroups-1.3.3/extern -std=gnu++11 -O3 -Wall -Wextra -Iinclude/eigen3 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -c src/knuth-bendix.cpp  -fPIC -DPIC -o src/.libs/libsemigroups_la-knuth-bendix.o
 In file included from src/knuth-bendix.cpp:31:
 /home/abuild/rpmbuild/BUILD/libsemigroups-1.3.3/include/libsemigroups/obvinf.hpp:72:10: fatal error: Eigen/Core: No such file or directory
    72 | #include <Eigen/Core>
```

**Comment by james-d-mitchell** [comment]
Hi @bmwiedemann, that looks like another issue altogether, can you possible either post the `config.log` file or a url so I can have a look at the relevant logs?

**Comment by bmwiedemann** [comment]
I found that other issue has meanwhile been fixed in
https://build.opensuse.org/package/view_file/science/eigen3/eigen3.changes
> - Drop eigen_pkgconfig.patch: the includedir now needs to be
>  specified relative to CMAKE_INSTALL_PREFIX, so this patch causes
>  the includedir in the pkgconfig file to be erroneous
>  ([boo#1178139](https://bugzilla.opensuse.org/show_bug.cgi?id=1178139)).

So now I could test your patch

```
 tests/test-froidure-pin-transf.cpp:385: FAILED:
   REQUIRE( S.max_threads() == 2 )
 with expansion:
   1 == 2

test cases:     420 |     419 passed | 1 failed
assertions: 1027815 | 1027814 passed | 1 failed
```

If you want to test yourself, you can do on Debian or openSUSE (with a [free account](https://idp-portal.suse.com)):
```bash
osc checkout science/libsemigroups && cd $_
wget https://github.com/libsemigroups/libsemigroups/pull/256.patch
edit libsemigroups.spec
# add on a new line after line 27:  Patch99: 256.patch
osc build --noservice -j1 --vm-type=kvm openSUSE_Tumbleweed
```

**Comment by james-d-mitchell** [comment]
Thanks @bmwiedemann I've fixed the newest issue too! I also tried to test it myself on openSUSE but had no luck (I created an account but wasn't able to login unfortunately). Any chance you could confirm if this resolves the issues?

**Comment by bmwiedemann** [comment]
Tested the current version of this patch and it makes tests pass now.

I checked that your user looks fine in our account system, but maybe you need to login to https://build.opensuse.org first, because it does [not know about you yet](https://build.opensuse.org/users/james-d-mitchell).

**Pull request merged**
