### PR TITLE
Update gabow.hpp for v1/3

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Ready for review if the CI passes

**Comment by james-d-mitchell** [comment]
If you could run iwyu on the files in this PR too, then I'd be most grateful @Joseph-Edwards

**Comment by Joseph-Edwards** [comment]
> Ready for review if the CI passes

We are expecting the pybind11 test to fail here too right @james-d-mitchell ?

**Review by Joseph-Edwards — APPROVED** [review]
All looks good to me. I'm happy to merge provided it's okay that the pybind11 test fails.

**Pull request merged**
