### PR TITLE
V3 work on `fpsemi-examples`

### PR DESCRIPTION
**Pull request by MTWhyte**
So far this checks each function in the file for whether it returns a semigroup or monoid presentation, updates the documentation to reflect this, and makes tests for this.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@MTWhyte I took the liberty of rebasing this onto the current v3 branch, I hope that's ok!

**Comment by james-d-mitchell** [comment]
I also fixed the linting and formatting.

**Comment by MTWhyte** [comment]
I think this is now is a state where it's worth being reviewed.

I've checked the tests are correctly categorised. On my system, complied with optimisation, no 'quick' test takes longer than 300ms to run (in fact the entire collection of these takes only about 900ms to run).

@james-d-mitchell there are a couple of TODOs, some of which I think will make more sense to you than to me. There are also a couple of presentations I think you've added that don't currently have documentation, but I'm not really sure what any of these actually are so I may leave this for you.

**Comment by MTWhyte** [comment]
The documentation shows up in a sort of weird way with a page I feel is unnecessary. I remember discussing this with @james-d-mitchell a month or so ago, and not being sure how to fix this, so I'll just leave it as is for now.

**Review by james-d-mitchell — APPROVED** [review]
Looks great, thanks @MTWhyte

**Pull request merged**
