### PR TITLE
sims: fix issue 557

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@orlitzky I think this resolves #557, but I can't currently test this, any chance you could confirm if this actually resolves the issue or not? Thanks!

**Comment by orlitzky** [comment]
Sure thing, thanks. It will take me about a day to compile GCC but I'll report back ASAP.

**Comment by orlitzky** [comment]
It works, thanks again.

**Comment by james-d-mitchell** [comment]
Thanks @orlitzky !

**Pull request merged**
