### PR TITLE
V3 make doxygen pretty

### PR DESCRIPTION
**Pull request by reiniscirpons**
This PR introduces a bunch of fixes to make the doxygen output look better, and to allow us to group classes and functions into separate pages.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Looks good @reiniscirpons can you maybe undelete the old-source directory in case we want to transfer some of the content to the document groups? Thanks!

**Comment by reiniscirpons** [comment]
@james-d-mitchell Undeleted the `old-source` directory, was a bit overzealous with the deletes

**Comment by james-d-mitchell** [comment]
Thanks @reiniscirpons Good to go?

**Comment by reiniscirpons** [comment]
Yep, this should now be good to merge

**Pull request merged**
